name: Create .env file
description: This action creates .env file from the specified multiline variables
inputs:
  env: 
    required: true
    description:  Multiline Environment Variables
outputs:
  status:
    description: failed | success
  envs:
    description: space separated list of environment variables
runs:
  using: node16
  main: dist/index.js
